### ISSUE TITLE
train_config_part0.yaml

### ISSUE THREAD

**Issue by Seema3996** [sneddy/kaggle-pneumathorax#6]
Hi @sneddy 
I am trying to implement your model. It works fine until this line
`python Train.py experiments/albunet_valid/train_config_part0.yaml. `
On running this it gives an error as _**Nonetype object has no attribute shape**_. I think that the dataset is not being served. I have made changes to the path in `Pneumadataset.py` as well as the DATA_DIRECTORY in `train_config_part0.yaml` to my path and run the `Train.py `file. But it still doesn't work. Am I missing out on anything? It might be a silly error but any help would be appreciated.
Attaching the screenshot of the error
![error](https://user-images.githubusercontent.com/59051961/71171350-8ffcf000-2283-11ea-933e-3713b1cfeb22.png)

**Comment by sneddy** [comment]
> Hi @sneddy
> I am trying to implement your model. It works fine until this line
> `python Train.py experiments/albunet_valid/train_config_part0.yaml. `
> On running this it gives an error as _**Nonetype object has no attribute shape**_. I think that the dataset is not being served. I have made changes to the path in `Pneumadataset.py` as well as the DATA_DIRECTORY in `train_config_part0.yaml` to my path and run the `Train.py `file. But it still doesn't work. Am I missing out on anything? It might be a silly error but any help would be appreciated.
> Attaching the screenshot of the error
> ![error](https://user-images.githubusercontent.com/59051961/71171350-8ffcf000-2283-11ea-933e-3713b1cfeb22.png)

Seems like you don't put input folder to right place

**Comment by Seema3996** [comment]
**Thank you for your response!**
Yes, that might be the problem. I have my input folder outside the `pneumothorax-segmentation ` folder rest of the file structure is the same. I did add the exact paths to the files but still, I will put all the folders exactly in the places as shown in the file structure and see if it works.
