### ISSUE TITLE
Regarding fold splitting

### ISSUE THREAD

**Issue by kailasdayanandan** [sneddy/kaggle-pneumathorax#7]
Is there any specific pattern in the identifying the images for different folds ?
How was this file train_folds_5.csv generated ?

**Comment by sneddy** [comment]
Seems like it was something like:
```python
df['fold_id'] = np.arange(df.shape[0])
df['fold_id'] = df['fold_id'].shuffle() % n_folds
```

**Comment by kailasdayanandan** [comment]
ok. thanks for the reply.. 
just wanted to know if some specific technique was used to split.
